apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  selector:
    matchLabels:
      app: employee-pod
  template:
    metadata:
      labels:
        app: employee-pod
    spec:
      containers:
      - name: employee-container
        image: acryaronz.azurecr.io/employees:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
